import Foundation
import os

// MARK: - CockpitBrainError

enum CockpitBrainError: LocalizedError, Sendable {
    case projectPathNotFound(String)
    case invalidPRDJson(String)
    case transverseCategoryNotFound(String)
    case specialistNotFound(String)
    case fileSystemError(String)

    var errorDescription: String? {
        switch self {
        case .projectPathNotFound(let path):
            return "Project path does not exist: \(path)"
        case .invalidPRDJson(let detail):
            return "Invalid PRD JSON: \(detail)"
        case .transverseCategoryNotFound(let name):
            return "No transverse category '\(name)' found in COP"
        case .specialistNotFound(let name):
            return "No specialist '\(name)' found in COP triggers"
        case .fileSystemError(let detail):
            return "File system error: \(detail)"
        }
    }
}

// MARK: - CockpitOrchestrationPlan

/// Cockpit Orchestration Plan generated by analyzing project context and PRD.
struct CockpitOrchestrationPlan: Codable, Sendable {
    let projectName: String
    let projectType: String
    let domain: String
    let marketContext: String
    let transverseProductions: [TransverseCategory]
    let specialistTriggers: [SpecialistTrigger]
    let metaAgentConfig: MetaAgentConfig
    let deliverablesPath: String
    let createdAt: String
}

// MARK: - TransverseCategory

/// A category of transverse deliverables (marketing, documentation, strategy, etc.).
struct TransverseCategory: Codable, Sendable {
    let category: String
    let deliverables: [String]
    let priority: String
}

// MARK: - SpecialistTrigger

/// A trigger condition that activates a specialist agent.
struct SpecialistTrigger: Codable, Sendable {
    let condition: String
    let specialist: String
    let reason: String
}

// MARK: - MetaAgentConfig

/// Configuration for the META monitor agent.
struct MetaAgentConfig: Codable, Sendable {
    let capabilities: [String]
    let monitoringIntervalMs: Int
    let autonomyLevel: String
}

// MARK: - AdaptationAction

/// An action recommended by the adaptation engine based on session state.
struct AdaptationAction: Codable, Sendable {
    let action: String
    let targetSlot: String?
    let reason: String
}

// MARK: - CockpitBrainService

/// Autonomous orchestration layer above coding agents.
/// Generates a COP (Cockpit Orchestration Plan) that drives transverse
/// productions, specialist triggers, and a META monitor agent.
actor CockpitBrainService {

    private let logger = Logger(subsystem: "com.xroads", category: "CockpitBrain")

    // MARK: - Specialist Rules

    /// Specialist trigger rules: (keywords, specialist name, reason).
    private static let specialistRules: [([String], String, String)] = [
        (
            ["auth", "login", "password", "session", "oauth", "jwt", "permission"],
            "security-auditor",
            "Authentication and authorization code requires security review"
        ),
        (
            ["payment", "billing", "subscription", "stripe", "invoice", "checkout"],
            "fintech-compliance",
            "Payment processing code must comply with financial regulations"
        ),
        (
            ["api", "endpoint", "rest", "graphql", "sdk", "webhook"],
            "dx-specialist",
            "API surface needs developer experience review"
        ),
        (
            ["data", "pipeline", "etl", "migration", "batch", "transform"],
            "data-quality",
            "Data processing pipelines need quality and validation review"
        ),
        (
            ["deploy", "infrastructure", "ci", "cd", "kubernetes", "docker", "terraform"],
            "devops-specialist",
            "Infrastructure code needs operational review"
        ),
        (
            ["accessibility", "a11y", "aria", "screen-reader", "wcag"],
            "accessibility-specialist",
            "UI code needs accessibility compliance review"
        ),
        (
            ["performance", "cache", "latency", "throughput", "benchmark"],
            "performance-specialist",
            "Performance-sensitive code needs optimization review"
        ),
    ]

    // MARK: - COP Generation

    /// Generate a Cockpit Orchestration Plan by analyzing project context and PRD.
    ///
    /// - Parameters:
    ///   - projectPath: Path to the project directory
    ///   - prdJson: JSON string of the PRD
    /// - Returns: Generated CockpitOrchestrationPlan
    func generateCOP(projectPath: String, prdJson: String) throws -> CockpitOrchestrationPlan {
        let fileManager = FileManager.default
        guard fileManager.fileExists(atPath: projectPath) else {
            throw CockpitBrainError.projectPathNotFound(projectPath)
        }

        guard let prdData = prdJson.data(using: .utf8),
              let prd = try? JSONSerialization.jsonObject(with: prdData) as? [String: Any] else {
            throw CockpitBrainError.invalidPRDJson("Could not parse JSON")
        }

        // Extract project name from path
        let projectName = URL(fileURLWithPath: projectPath).lastPathComponent

        // Detect project characteristics
        let projectType = detectProjectType(projectPath: projectPath)
        let domain = detectDomainFromPRD(prd)
        let marketContext = detectMarketContext(projectPath: projectPath)

        // Build transverse productions
        let transverseProductions = buildTransverseProductions(projectType: projectType, domain: domain)

        // Detect specialist triggers from PRD
        let specialistTriggers = detectSpecialistNeedsFromPRD(prd)

        // Configure META agent
        var capabilities = ["qa", "doc_gen", "git_master"]
        if domain == "security" || specialistTriggers.contains(where: { $0.specialist == "security-auditor" }) {
            capabilities.append("security_scan")
        }

        let metaAgentConfig = MetaAgentConfig(
            capabilities: capabilities,
            monitoringIntervalMs: 30_000,
            autonomyLevel: marketContext == "regulated" ? "limited" : "full"
        )

        let deliverablesPath = "\(projectPath)/.crossroads/deliverables/"

        let cop = CockpitOrchestrationPlan(
            projectName: projectName,
            projectType: projectType,
            domain: domain,
            marketContext: marketContext,
            transverseProductions: transverseProductions,
            specialistTriggers: specialistTriggers,
            metaAgentConfig: metaAgentConfig,
            deliverablesPath: deliverablesPath,
            createdAt: ISO8601DateFormatter().string(from: Date())
        )

        // Persist COP to .crossroads/cockpit-plan.json
        let crossroadsDir = URL(fileURLWithPath: projectPath).appendingPathComponent(".crossroads")
        try fileManager.createDirectory(at: crossroadsDir, withIntermediateDirectories: true)

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let copData = try encoder.encode(cop)
        try copData.write(to: crossroadsDir.appendingPathComponent("cockpit-plan.json"))

        logger.info("Generated COP for '\(projectName)': type=\(projectType), domain=\(domain)")
        return cop
    }

    // MARK: - COP Loading

    /// Load a previously generated COP from disk.
    ///
    /// - Parameter projectPath: Path to the project directory
    /// - Returns: The COP if one exists on disk, nil otherwise
    func getCOP(projectPath: String) -> CockpitOrchestrationPlan? {
        let copURL = URL(fileURLWithPath: projectPath)
            .appendingPathComponent(".crossroads")
            .appendingPathComponent("cockpit-plan.json")

        guard let data = try? Data(contentsOf: copURL) else { return nil }
        return try? JSONDecoder().decode(CockpitOrchestrationPlan.self, from: data)
    }

    // MARK: - Skill Generation

    /// Generate a SKILL.md for the META monitor agent.
    ///
    /// - Parameter cop: The Cockpit Orchestration Plan
    /// - Returns: Markdown skill definition
    func generateMetaSkill(cop: CockpitOrchestrationPlan) -> String {
        let riskAreas = cop.specialistTriggers.map(\.specialist)
        let riskAreasStr = riskAreas.isEmpty ? "none identified" : riskAreas.joined(separator: ", ")

        let testCmd: String
        switch cop.projectType {
        case "cli", "library":
            testCmd = "cargo test"
        default:
            testCmd = "npm test"
        }

        let capabilitiesList = cop.metaAgentConfig.capabilities
            .map { "- \($0)" }
            .joined(separator: "\n")

        return """
        # META Monitor Skill

        You are the code quality monitor for the **\(cop.projectName)** project.

        ## Your responsibilities:
        - Monitor all git worktrees for code quality issues
        - Run `\(testCmd)` to verify test coverage after each agent iteration
        - Check for security vulnerabilities in new code
        - Auto-generate documentation updates when APIs change
        - Flag merge conflicts early and report to the cockpit
        - Report status every iteration

        ## Project context:
        - **Type:** \(cop.projectType)
        - **Domain:** \(cop.domain)
        - **Market:** \(cop.marketContext)
        - **Risk areas:** \(riskAreasStr)

        ## Capabilities:
        \(capabilitiesList)

        ## You have access to:
        - Git operations (diff, log, merge, worktree list)
        - Test runners (`\(testCmd)`)
        - File system (read/write .md files in .crossroads/)
        - Conflict detection between worktrees

        ## Workflow:
        1. Check each active worktree for uncommitted changes
        2. Run tests in each worktree
        3. Compare diffs between worktrees for potential conflicts
        4. Update `.crossroads/meta-status.json` with findings
        5. Create alerts for any issues found
        """
    }

    /// Generate a SKILL.md for a transverse production agent.
    ///
    /// - Parameters:
    ///   - cop: The Cockpit Orchestration Plan
    ///   - category: The transverse category name
    /// - Returns: Markdown skill definition
    func generateTransverseSkill(cop: CockpitOrchestrationPlan, category: String) throws -> String {
        guard let transverse = cop.transverseProductions.first(where: { $0.category == category }) else {
            throw CockpitBrainError.transverseCategoryNotFound(category)
        }

        let deliverablesList = transverse.deliverables
            .map { "- [ ] `\($0).md`" }
            .joined(separator: "\n")

        let specialistContext: String
        if cop.specialistTriggers.isEmpty {
            specialistContext = "No specialist concerns identified."
        } else {
            specialistContext = cop.specialistTriggers
                .map { "- **\($0.specialist)**: \($0.reason)" }
                .joined(separator: "\n")
        }

        let categoryTitle = capitalizeFirst(category)

        return """
        # \(categoryTitle) Production Skill

        You are producing **\(category)** deliverables for the **\(cop.projectName)** project.

        ## Deliverables to create:
        \(deliverablesList)

        ## Quality requirements:
        - Each deliverable must be a standalone `.md` file
        - Each deliverable must be actionable and specific (no filler content)
        - Reference actual project context, features, and domain terminology
        - Save all files to: `.crossroads/deliverables/\(category)/`

        ## Project context:
        - **Project:** \(cop.projectName)
        - **Type:** \(cop.projectType)
        - **Domain:** \(cop.domain)
        - **Market:** \(cop.marketContext)
        - **Priority for this category:** \(transverse.priority)

        ## Specialist considerations:
        \(specialistContext)

        ## Workflow:
        1. Read the project README and PRD to understand features
        2. Create each deliverable file in order of importance
        3. Cross-reference deliverables for consistency
        4. Write a `_index.md` summarizing all deliverables produced
        """
    }

    /// Generate a SKILL.md for a specialist agent.
    ///
    /// - Parameters:
    ///   - cop: The Cockpit Orchestration Plan
    ///   - specialist: The specialist name
    /// - Returns: Markdown skill definition
    func generateSpecialistSkill(cop: CockpitOrchestrationPlan, specialist: String) throws -> String {
        guard let trigger = cop.specialistTriggers.first(where: { $0.specialist == specialist }) else {
            throw CockpitBrainError.specialistNotFound(specialist)
        }

        let focusAreas: [String]
        switch specialist {
        case "security-auditor":
            focusAreas = [
                "Authentication flow correctness",
                "Session management security",
                "Input validation and sanitization",
                "Secret handling (no hardcoded keys)",
                "OWASP Top 10 compliance",
            ]
        case "fintech-compliance":
            focusAreas = [
                "PCI DSS compliance for payment handling",
                "Idempotency in financial transactions",
                "Audit trail completeness",
                "Error handling for payment failures",
                "Data encryption at rest and in transit",
            ]
        case "dx-specialist":
            focusAreas = [
                "API consistency and naming conventions",
                "Error response format standardization",
                "Rate limiting documentation",
                "SDK usability and code examples",
                "Versioning strategy",
            ]
        case "data-quality":
            focusAreas = [
                "Data validation at pipeline boundaries",
                "Schema evolution handling",
                "Idempotent processing guarantees",
                "Error recovery and dead letter queues",
                "Data lineage tracking",
            ]
        case "devops-specialist":
            focusAreas = [
                "CI/CD pipeline reliability",
                "Infrastructure as code best practices",
                "Monitoring and alerting coverage",
                "Rollback procedures",
                "Secret management in deployment",
            ]
        case "accessibility-specialist":
            focusAreas = [
                "WCAG 2.1 AA compliance",
                "Screen reader compatibility",
                "Keyboard navigation support",
                "Color contrast ratios",
                "ARIA attribute correctness",
            ]
        case "performance-specialist":
            focusAreas = [
                "Query optimization and N+1 detection",
                "Cache invalidation strategy",
                "Memory usage profiling",
                "Response time budgets",
                "Load testing coverage",
            ]
        default:
            focusAreas = [
                "Code quality review",
                "Best practices compliance",
                "Documentation accuracy",
            ]
        }

        let focusList = focusAreas.map { "- \($0)" }.joined(separator: "\n")
        let specialistTitle = specialist.split(separator: "-")
            .map { capitalizeFirst(String($0)) }
            .joined(separator: " ")

        return """
        # \(specialistTitle) Specialist Skill

        You are the **\(specialist)** for the **\(cop.projectName)** project.

        ## Trigger condition:
        \(trigger.condition)

        ## Reason for activation:
        \(trigger.reason)

        ## Focus areas:
        \(focusList)

        ## Project context:
        - **Type:** \(cop.projectType)
        - **Domain:** \(cop.domain)
        - **Market:** \(cop.marketContext)

        ## Workflow:
        1. Review all code changes in active worktrees related to your domain
        2. Identify vulnerabilities, compliance gaps, or quality issues
        3. Write findings to `.crossroads/deliverables/specialist/\(specialist)-report.md`
        4. Flag critical issues as blocking gates
        5. Provide specific remediation steps for each finding

        ## Output format:
        Each finding should include:
        - **Severity**: critical / high / medium / low
        - **Location**: file path and line range
        - **Description**: what the issue is
        - **Remediation**: how to fix it
        """
    }

    // MARK: - Deliverables Structure

    /// Create the deliverables directory structure under .crossroads/.
    ///
    /// - Parameters:
    ///   - projectPath: Path to the project directory
    ///   - cop: The Cockpit Orchestration Plan
    func createDeliverablesStructure(projectPath: String, cop: CockpitOrchestrationPlan) throws {
        let fileManager = FileManager.default
        let baseURL = URL(fileURLWithPath: projectPath)
            .appendingPathComponent(".crossroads")
            .appendingPathComponent("deliverables")

        // Standard directories
        let dirs = ["marketing", "research", "documentation", "strategy", "ops", "specialist"]
        for dir in dirs {
            let dirURL = baseURL.appendingPathComponent(dir)
            try fileManager.createDirectory(at: dirURL, withIntermediateDirectories: true)
        }

        // Write a manifest of expected deliverables
        var manifest = "# Deliverables Manifest\n\n"
        manifest += "Project: \(cop.projectName)\n"
        manifest += "Generated: \(cop.createdAt)\n\n"

        for cat in cop.transverseProductions {
            manifest += "## \(capitalizeFirst(cat.category)) (priority: \(cat.priority))\n"
            for d in cat.deliverables {
                manifest += "- [ ] \(d).md\n"
            }
            manifest += "\n"
        }

        if !cop.specialistTriggers.isEmpty {
            manifest += "## Specialist Reports\n"
            for t in cop.specialistTriggers {
                manifest += "- [ ] \(t.specialist)-report.md\n"
            }
            manifest += "\n"
        }

        let manifestURL = baseURL.appendingPathComponent("_manifest.md")
        try manifest.write(to: manifestURL, atomically: true, encoding: .utf8)

        logger.info("Created deliverables structure at \(baseURL.path)")
    }

    // MARK: - Specialist Detection

    /// Detect specialist needs from story titles and descriptions.
    ///
    /// - Parameter stories: Array of (title, description) tuples
    /// - Returns: Array of triggered specialists
    func detectSpecialistNeeds(stories: [(String, String)]) -> [SpecialistTrigger] {
        var textPool = ""
        for (title, description) in stories {
            textPool += title + " " + description + " "
        }

        let lower = textPool.lowercased()
        var triggers: [SpecialistTrigger] = []
        var seenSpecialists: Set<String> = []

        for (keywords, specialist, reason) in Self.specialistRules {
            let matchedKeywords = keywords.filter { lower.contains($0) }

            if !matchedKeywords.isEmpty && !seenSpecialists.contains(specialist) {
                let condition = matchedKeywords
                    .map { "domain contains \"\($0)\"" }
                    .joined(separator: " OR ")

                triggers.append(SpecialistTrigger(
                    condition: condition,
                    specialist: specialist,
                    reason: reason
                ))
                seenSpecialists.insert(specialist)
            }
        }

        return triggers
    }

    // MARK: - Adaptation Actions

    /// Analyze current slot states and session cost to return adaptation actions.
    ///
    /// Rules:
    /// - Error slots > 3: focus debugging
    /// - Individual error slots: target debugging
    /// - Budget > 80%: switch to cheaper model
    /// - All coding complete: activate transverse
    /// - 50%+ coding complete: activate transverse in parallel
    /// - Multiple error slots with similar tasks: pause and resolve conflicts
    /// - No running slots but incomplete: restart stalled
    ///
    /// - Parameters:
    ///   - slots: Current agent slots
    ///   - sessionCost: Current session cost summary
    /// - Returns: Array of recommended adaptation actions
    func getAdaptationActions(slots: [AgentSlot], sessionCost: UsageSummary) -> [AdaptationAction] {
        var actions: [AdaptationAction] = []

        let totalSlots = slots.count
        let doneSlots = slots.filter { $0.status == .done }.count
        let errorSlots = slots.filter { $0.status == .error }
        let runningSlots = slots.filter { $0.status == .running }.count

        // Rule: Too many test failures -> focus debugging
        if errorSlots.count > 3 {
            actions.append(AdaptationAction(
                action: "focus_debugging",
                targetSlot: nil,
                reason: "\(errorSlots.count) slots in error state — prioritize debugging before proceeding"
            ))
        }

        // Rule: Specific error slots -> target them for debugging
        for slot in errorSlots {
            actions.append(AdaptationAction(
                action: "focus_debugging",
                targetSlot: slot.id.uuidString,
                reason: "Slot \(slot.id) (index \(slot.slotIndex)) failed: \(slot.currentTask ?? "unknown error")"
            ))
        }

        // Rule: Budget > 80% -> switch to cheaper model
        let budgetCents = 2500
        let percentUsed = budgetCents > 0
            ? (Double(sessionCost.totalCostCents) / Double(budgetCents)) * 100.0
            : 0.0

        if percentUsed > 80.0 {
            actions.append(AdaptationAction(
                action: "switch_model",
                targetSlot: nil,
                reason: String(format: "Budget at %.0f%% (%dc / %dc) — switch to cheaper model for remaining work",
                               percentUsed, sessionCost.totalCostCents, budgetCents)
            ))
        }

        // Rule: Coding complete -> activate transverse
        if totalSlots > 0 && doneSlots == totalSlots {
            actions.append(AdaptationAction(
                action: "activate_transverse",
                targetSlot: nil,
                reason: "All coding slots completed — activate transverse production agents"
            ))
        } else if totalSlots > 0 {
            let progress = (Double(doneSlots) / Double(totalSlots)) * 100.0
            if progress >= 50.0 {
                actions.append(AdaptationAction(
                    action: "activate_transverse",
                    targetSlot: nil,
                    reason: String(format: "Coding at %.0f%% (%d/%d done) — transverse agents can start in parallel",
                                   progress, doneSlots, totalSlots)
                ))
            }
        }

        // Rule: Conflict detected (multiple error slots with similar tasks)
        if errorSlots.count >= 2 {
            let errorTasks = errorSlots.compactMap(\.currentTask)
            let hasConflict = zip(errorTasks, errorTasks.dropFirst()).contains { pair in
                let wordsA = Set(pair.0.split(separator: " ").map { $0.lowercased() })
                let wordsB = Set(pair.1.split(separator: " ").map { $0.lowercased() })
                return wordsA.intersection(wordsB).count >= 2
            }

            if hasConflict {
                actions.append(AdaptationAction(
                    action: "pause_and_resolve",
                    targetSlot: nil,
                    reason: "Potential conflict detected between error slots — pause and resolve before continuing"
                ))
            }
        }

        // Rule: No running slots but session should be active
        if runningSlots == 0 && doneSlots < totalSlots && totalSlots > 0 {
            actions.append(AdaptationAction(
                action: "restart_stalled",
                targetSlot: nil,
                reason: String(format: "No running slots (%d/%d done) — restart stalled agents",
                               doneSlots, totalSlots)
            ))
        }

        return actions
    }

    // MARK: - Private Helpers

    /// Detect project type from config files in the project directory.
    private func detectProjectType(projectPath: String) -> String {
        let fileManager = FileManager.default
        let packageJsonPath = "\(projectPath)/package.json"
        let cargoTomlPath = "\(projectPath)/Cargo.toml"
        let packageSwiftPath = "\(projectPath)/Package.swift"
        let pubspecPath = "\(projectPath)/pubspec.yaml"
        let gradlePath = "\(projectPath)/build.gradle"
        let gradleKtsPath = "\(projectPath)/build.gradle.kts"

        if fileManager.fileExists(atPath: packageJsonPath) {
            let content = (try? String(contentsOfFile: packageJsonPath, encoding: .utf8)) ?? ""
            if let data = content.data(using: .utf8),
               let pkg = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
               let deps = pkg["dependencies"] as? [String: Any] {

                let hasNext = deps["next"] != nil
                let hasReact = deps["react"] != nil
                let hasExpress = deps["express"] != nil
                let hasFastify = deps["fastify"] != nil

                if hasNext || hasReact { return "saas" }
                if hasExpress || hasFastify { return "api" }
            }

            // Check for CLI indicators
            if let data = content.data(using: .utf8),
               let pkg = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
               pkg["bin"] != nil {
                return "cli"
            }

            return "web"
        }

        if fileManager.fileExists(atPath: cargoTomlPath) {
            let content = ((try? String(contentsOfFile: cargoTomlPath, encoding: .utf8)) ?? "").lowercased()

            if content.contains("[[bin]]") || (content.contains("crate-type") && content.contains("\"bin\"")) {
                return "cli"
            }
            if content.contains("actix") || content.contains("axum") || content.contains("rocket") || content.contains("warp") {
                return "api"
            }
            if content.contains("[lib]") && !content.contains("[[bin]]") {
                return "library"
            }
            return "cli"
        }

        if fileManager.fileExists(atPath: packageSwiftPath) {
            return "cli" // Swift package, default to CLI
        }

        if fileManager.fileExists(atPath: pubspecPath) {
            return "mobile"
        }

        if fileManager.fileExists(atPath: gradlePath) || fileManager.fileExists(atPath: gradleKtsPath) {
            let androidPath = "\(projectPath)/android"
            if fileManager.fileExists(atPath: androidPath) {
                return "mobile"
            }
            return "api"
        }

        return "web"
    }

    /// Detect domain from PRD content using keyword matching.
    private func detectDomainFromPRD(_ prd: [String: Any]) -> String {
        var textPool = ""

        if let name = prd["feature_name"] as? String {
            textPool += name + " "
        }
        if let desc = prd["description"] as? String {
            textPool += desc + " "
        }
        if let stories = prd["user_stories"] as? [[String: Any]] {
            for story in stories {
                if let title = story["title"] as? String {
                    textPool += title + " "
                }
                if let desc = story["description"] as? String {
                    textPool += desc + " "
                }
            }
        }

        let lower = textPool.lowercased()

        let domainRules: [(String, [String])] = [
            ("fintech", ["payment", "billing", "subscription", "invoice", "stripe", "checkout", "wallet", "transaction"]),
            ("health", ["patient", "medical", "health", "diagnosis", "appointment", "prescription", "clinical"]),
            ("security", ["auth", "login", "password", "session", "token", "oauth", "permission", "role", "rbac", "jwt"]),
            ("devtools", ["api", "endpoint", "rest", "graphql", "sdk", "cli", "developer", "plugin", "extension"]),
            ("ecommerce", ["cart", "product", "catalog", "order", "shipping", "inventory"]),
            ("analytics", ["dashboard", "metric", "report", "chart", "analytics", "tracking", "event"]),
            ("data", ["pipeline", "etl", "data", "transform", "migration", "batch", "stream"]),
            ("infra", ["deploy", "infrastructure", "ci", "cd", "kubernetes", "docker", "terraform"]),
            ("ai", ["model", "ml", "prediction", "training", "inference", "embedding", "llm"]),
            ("messaging", ["chat", "message", "notification", "email", "sms", "push"]),
        ]

        var bestDomain = "general"
        var bestScore = 0

        for (domain, keywords) in domainRules {
            let score = keywords.filter { lower.contains($0) }.count
            if score > bestScore {
                bestScore = score
                bestDomain = domain
            }
        }

        return bestDomain
    }

    /// Detect market context from README.md content.
    private func detectMarketContext(projectPath: String) -> String {
        let readmePath = "\(projectPath)/README.md"
        let content = ((try? String(contentsOfFile: readmePath, encoding: .utf8)) ?? "").lowercased()

        if content.contains("compliance") || content.contains("regulation") || content.contains("hipaa")
            || content.contains("gdpr") || content.contains("pci") || content.contains("sox") {
            return "regulated"
        }

        if content.contains("competitor") || content.contains("alternative to")
            || content.contains("vs ") || content.contains("compared to") {
            return "competitive"
        }

        return "greenfield"
    }

    /// Build transverse production categories based on project type and domain.
    private func buildTransverseProductions(projectType: String, domain: String) -> [TransverseCategory] {
        var categories: [TransverseCategory] = []

        // All projects need documentation
        let docDeliverables: [String]
        switch projectType {
        case "cli":
            docDeliverables = ["man-page", "install-guide", "usage-examples", "changelog"]
        case "api":
            docDeliverables = ["api-reference", "sdk-guide", "authentication-guide", "deploy-guide", "changelog"]
        case "library":
            docDeliverables = ["api-reference", "getting-started", "migration-guide", "changelog"]
        default:
            docDeliverables = ["README", "deploy-guide", "architecture-overview", "changelog"]
        }

        categories.append(TransverseCategory(
            category: "documentation",
            deliverables: docDeliverables,
            priority: "high"
        ))

        // SaaS and web projects need marketing
        if projectType == "saas" || projectType == "web" {
            categories.append(TransverseCategory(
                category: "marketing",
                deliverables: ["landing-page-copy", "value-proposition", "feature-comparison", "onboarding-flow-copy"],
                priority: "high"
            ))

            categories.append(TransverseCategory(
                category: "strategy",
                deliverables: ["pricing-model", "go-to-market-plan", "user-persona-profiles"],
                priority: "medium"
            ))
        }

        // API projects need developer-focused research
        if projectType == "api" {
            categories.append(TransverseCategory(
                category: "research",
                deliverables: ["developer-personas", "integration-patterns", "rate-limit-strategy"],
                priority: "medium"
            ))
        }

        // SaaS projects need competitive research
        if projectType == "saas" {
            categories.append(TransverseCategory(
                category: "research",
                deliverables: ["competitive-analysis", "market-sizing", "user-interview-template"],
                priority: "medium"
            ))
        }

        // Domain-specific additions
        switch domain {
        case "fintech":
            categories.append(TransverseCategory(
                category: "ops",
                deliverables: ["compliance-checklist", "audit-trail-spec", "incident-response-plan"],
                priority: "high"
            ))
        case "health":
            categories.append(TransverseCategory(
                category: "ops",
                deliverables: ["hipaa-compliance-checklist", "data-handling-policy", "consent-flow-spec"],
                priority: "high"
            ))
        case "security":
            categories.append(TransverseCategory(
                category: "ops",
                deliverables: ["security-policy", "threat-model", "penetration-test-plan"],
                priority: "high"
            ))
        default:
            break
        }

        return categories
    }

    /// Detect specialist needs directly from a parsed PRD dictionary.
    private func detectSpecialistNeedsFromPRD(_ prd: [String: Any]) -> [SpecialistTrigger] {
        guard let stories = prd["user_stories"] as? [[String: Any]] else { return [] }

        let storyPairs: [(String, String)] = stories.map { story in
            let title = (story["title"] as? String) ?? ""
            let desc = (story["description"] as? String) ?? ""
            return (title, desc)
        }

        return detectSpecialistNeeds(stories: storyPairs)
    }

    /// Capitalize the first letter of a string.
    private func capitalizeFirst(_ s: String) -> String {
        guard let first = s.first else { return "" }
        return first.uppercased() + s.dropFirst()
    }
}
